from debian:buster

RUN apt-get update
RUN apt-get -y install nginx
RUN nginx

RUN apt-get -y install openssl
RUN openssl req -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=KR/ST=Seoul/L=Seoul/O=42Seoul/OU=Lee/CN=localhost" -keyout localhost.dev.key -out localhost.dev.crt
RUN mv localhost.dev.crt /etc/ssl/certs/
RUN mv localhost.dev.key /etc/ssl/private/
RUN chmod 600 etc/ssl/certs/localhost.dev.crt etc/ssl/private/localhost.dev.key

RUN apt-get -y install vim
COPY ./srcs/default /etc/nginx/sites-available/default
COPY ./srcs/index.php /var/www/html/index.php

RUN apt-get -y install php-fpm

RUN apt-get -y install mariadb-server php-mysql php-mbstring
RUN apt-get -y install wget
RUN wget https://wordpress.org/latest.tar.gz
RUN tar -xvf latest.tar.gz
RUN mv wordpress/ /var/www/html/
RUN chown -R www-data:www-data /var/www/html/wordpress
COPY ./srcs/wp-config.php /var/www/html/wordpress/wp-config.php 

RUN	service mysql start &&\
	echo "CREATE DATABASE if not exits wordpress;" | mysql -u root --skip-password && \
	echo "CREATE USER if not exits 'huchoi'@'localhost' IDENTIFIED BY 'huchoi';" | mysql -u root --skip-password &&\
	echo "GRANT ALL PRIVILEGES ON wordpress.* TO 'huchoi'@'localhost' WITH GRANT OPTION;" | mysql -u root --skip-password &&\
	echo "FLUSH PRIVILEGES;" | mysql -u root --skip-password

RUN service php7.3-fpm restart

RUN wget https://files.phpmyadmin.net/phpMyAdmin/5.0.2/phpMyAdmin-5.0.2-all-languages.tar.gz
RUN tar -xvf phpMyAdmin-5.0.2-all-languages.tar.gz
RUN mv phpMyAdmin-5.0.2-all-languages phpmyadmin
RUN mv phpmyadmin /var/www/html/
COPY ./srcs/config.inc.php /var/www/html/phpmyadmin/config.inc.php 
RUN service nginx reload
RUN service mysql start
RUN mysql < var/www/html/phpmyadmin/sql/create_tables.sql

EXPOS 80 443

CMD ./my_start.sh
