apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
      app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  minReadySeconds: 5
  template:
    metadata:
      name: telegraf
      labels:
        app: telegraf
    spec:
      restartPolicy: Always
      containers:
        - name: telegraf-container
          image: telegraf
          imagePullPolicy: Always
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
